# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90f83ffe7118b019332f2a9000c84e5c1a20458a0507711f94ba04c4c9db7147ae99be542e1874751e5a545b45fe8a9bc84a632920d8d29c684011a2380bf71

test:
  secret_key_base: 01d0244426d82895bed752046c0b936b980659151ff09f8039c1e876d086d86a96d3a13a8bae9368883b998026ca7dae71549ce0bff2aec66ebfd26daedecb40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
